namespace BrawlhallaReplayReader
{
    public static class Constants
    {
        public static readonly List<string> PlayerHeaders = new List<string> { "time", "name", "placement", "deaths", "hero", "map", "playerCount", "gameLength", "players", "version", "checksum", "isTeam", "teammates" };

        public static readonly List<string> GameHeaders = new List<string> { "time", "map", "version", "checksum", "players", "heroes", "deaths", "playerCount", "winner", "gameLength", "isTeam", "teams" };

        public static readonly Dictionary<int, string> Heroes = new Dictionary<int, string>{
            // It seems like 1 and 2 are unused
            { 3, "bodvar" },
            { 4, "cassidy" },
            { 5, "orion" },
            { 6, "lord_vrax" },
            { 7, "gnash" },
            { 8, "queen_nai" },
            { 9, "lucien" },
            { 10, "hatori" },
            { 11, "sir_roland" },
            { 12, "scarlet" },
            { 13, "thatch" },
            { 14, "ada" },
            { 15, "sentinel" },
            { 16, "teros" },
            { 17, "red_raptor" },
            { 18, "ember" },
            { 19, "brynn" },
            { 20, "asuri" },
            { 21, "barraza" },
            { 22, "ulgrim" },
            { 23, "azoth" },
            { 24, "koji" },
            { 25, "diana" },
            { 26, "jhala" },
            { 27, "loki" },
            { 28, "kor" },
            { 29, "wu_shang" },
            { 30, "val" },
            { 31, "ragnir" },
            { 32, "cross" },
            { 33, "mirage" },
            { 34, "nix" },
            { 35, "mordex" },
            { 36, "yumiko" },
            { 37, "artemis" },
            { 38, "caspian" },
            { 39, "sidra" },
            { 40, "xull" },
            { 41, "isaiah" },
            { 42, "kaya" },
            { 43, "jiro" },
            { 44, "lin_fei" },
            { 45, "zariel" },
            { 46, "rayman" },
            { 47, "dusk" },
            { 48, "fait" },
            { 49, "thor" },
            { 50, "petra" },
            { 51, "vector" },
            { 52, "volkov" },
            { 53, "onyx" },
            { 54, "jaeyun" },
            { 55, "mako" },
            { 56, "magyar" },
            { 57, "reno" },
            { 58, "munin" },
            { 59, "arcadia" },
            { 60, "ezio" },
            { 61, "seven" },
            { 62, "thea" },
            { 63, "tezca" },
            { 64, "vivi" },
            { 65, "imugi" },
            { 66, "king_zuva" },
            { 67, "priya" },
            { 68, "ransom" }
        };
    }
}